[package]
name = "s3-proxy"
version = "0.1.0"
edition = "2021"

[features]
default = ["management"]
management = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.0"
md-5 = "0.10.6"
askama = "0.16.0"
askama_web = { version = "0.16.0", features = ["axum-0.8"] }
async-trait = "0.1.91"
aws-credential-types = "1.3.0"
aws-sigv4 = { version = "1.5.1", features = ["sign-http"] }
aws-smithy-runtime-api = "1.14.0"
axum = { version = "0.8.9", features = ["http2", "multipart"] }
axum-extra = { version = "0.12.6", features = ["typed-header"] }
axum-route-error = "5.1.0"
config = { version = "0.15.25", default-features = false }
deadpool-redis = { version = "0.23.0", features = ["rt_tokio_1", "serde"] }
futures-util = "0.3.33"
headers = "0.4.1"
httpdate = "1.0.3"
opendal = {
    git = "https://github.com/apache/opendal.git",
    rev = "c171ae6b088a6471854bd4c2327abda9e8637fe8",
    features = [
        "services-b2",
        "services-cloudflare-kv",
        "services-compfs",
        "services-cos",
        "services-dashmap",
        "services-fs",
        "services-github",
        "services-koofr",
        "services-memory",
        "services-mini-moka",
        "services-moka",
        "services-obs",
        "services-oss",
        "services-s3",
        "services-seafile",
        "services-sled",
        "services-swift",
        "services-tos",
        "services-upyun",
        "services-vercel-blob",
        "services-webdav",
        "services-yandex-disk",
        "layers-tracing",
    ],
}
quick-xml = { version = "0.41.0", features = ["serialize", "async-tokio"] }
hex = "0.4.3"
rand = "0.10.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "tls-rustls", "any", "sqlite", "postgres"] }
time = { version = "0.3.54", features = ["formatting", "macros"] }
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = { version = "0.1.19", features = ["full"] }
tower = "0.5.3"
tower-http = { version = "0.7.0", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
urlencoding = "2.1.3"

[dev-dependencies]
assert_cmd = "2.2.2"
aws-config = {
    version = "1.10.1",
    default-features = false,
    features = ["behavior-version-latest", "default-https-client", "rt-tokio"],
}
aws-sdk-s3 = {
    version = "1.140.0",
    default-features = false,
    features = ["default-https-client", "http-1x", "rt-tokio", "sigv4a"],
}
